from PIL import ImageFont

DAY_SIZE = 150
MAX_DAY = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
HEADER_SIZE = 50
BORDER_TOP_LEFT = .05
BORDER_BOTTOM_LEFT = .95
TEXT_OFFSET = .04
MONTH_PER_LINE = 5
LINE_SIZE = 5
FONT_SIZE = 50
FONT = ImageFont.truetype("Consolas.ttf", size=FONT_SIZE)

__all__ = ["DAY_SIZE", "MAX_DAY", "HEADER_SIZE", "BORDER_TOP_LEFT", "BORDER_BOTTOM_LEFT", "TEXT_OFFSET",
           "MONTH_PER_LINE", "LINE_SIZE", "FONT_SIZE", "FONT"]
